apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sensehub-production

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/bransolo1/autoqual-api
    newTag: latest
  - name: ghcr.io/bransolo1/autoqual-web
    newTag: latest
  - name: ghcr.io/bransolo1/autoqual-worker
    newTag: latest

patches:
  - path: patch-ingress.yaml
  - path: patch-configmap.yaml
