import * as Joi from "joi";

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid("development", "test", "production").default("development"),
  DATABASE_URL: Joi.string().uri().required(),
  REDIS_HOST: Joi.string().default("localhost"),
  REDIS_PORT: Joi.number().default(6379),
  OPENSEARCH_URL: Joi.string().uri().required(),
  OPENSEARCH_USERNAME: Joi.string().allow("").optional(),
  OPENSEARCH_PASSWORD: Joi.string().allow("").optional(),
  S3_ENDPOINT: Joi.string().uri().required(),
  S3_REGION: Joi.string().default("us-east-1"),
  S3_ACCESS_KEY: Joi.string().required(),
  S3_SECRET_KEY: Joi.string().required(),
  S3_BUCKET: Joi.string().required(),
  AI_PROVIDER: Joi.string().valid("mock", "openai", "anthropic").default("mock"),
  EMBED_SECRET: Joi.string().min(16).required(),
  EMBED_COMPLETION_WEBHOOK_URL: Joi.string().allow("").uri(),
  OTEL_SERVICE_NAME: Joi.string().default("sensehub-api"),
  OTEL_EXPORTER_OTLP_ENDPOINT: Joi.string().uri(),
  WEB_BASE_URL: Joi.string().uri().required(),
  CORS_ORIGIN: Joi.string().required(),
  JWT_ISSUER: Joi.string().uri().allow("").optional(),
  JWT_AUDIENCE: Joi.string().allow("").optional(),
  JWT_JWKS_URL: Joi.string().uri().allow("").optional(),
  JWT_PUBLIC_KEY: Joi.string().allow("").optional(),
  JWT_SECRET: Joi.string().allow("").optional(),
  JWT_ALGORITHM: Joi.string().allow("").optional(),
  JWT_REQUIRE_JTI: Joi.boolean().default(false),
  AUDIT_RETENTION_ALLOW: Joi.boolean().default(false),
  AUDIT_RETENTION_DAYS: Joi.number().default(365),
  SSO_ENABLED: Joi.boolean().default(false),
  SSO_ISSUER_URL: Joi.string().uri().allow("").optional(),
  SSO_CLIENT_ID: Joi.string().allow("").optional(),
  SSO_CLIENT_SECRET: Joi.string().allow("").optional(),
  SSO_REDIRECT_URI: Joi.string().uri().allow("").optional(),
  SSO_ALLOWED_DOMAINS: Joi.string().allow("").optional(),
  SSO_GROUP_ROLE_MAP: Joi.string().allow("").optional(),
  SSO_DEFAULT_ROLE: Joi.string().allow("").optional(),
  SECRETS_PROVIDER: Joi.string().valid("env", "vault").default("env"),
  VAULT_ADDR: Joi.string().uri().allow("").optional(),
  VAULT_ROLE: Joi.string().allow("").optional(),
  VAULT_TOKEN: Joi.string().allow("").optional(),
  TOKEN_REVOCATION_PURGE_ENABLED: Joi.boolean().default(false),
  THROTTLE_TTL: Joi.number().default(60),
  THROTTLE_LIMIT: Joi.number().default(120),
}).unknown(true);
