apiVersion: v1
kind: ConfigMap
metadata:
  name: sensehub-config
data:
  WEB_BASE_URL: "https://staging.yourdomain.com"
  NEXT_PUBLIC_API_URL: "https://staging.yourdomain.com/api"
  CORS_ORIGIN: "https://staging.yourdomain.com"
