apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sensehub-ingress
spec:
  rules:
    - host: sensehub.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sensehub-api
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sensehub-web
                port:
                  number: 3000
