apiVersion: v1
kind: Secret
metadata:
  name: sensehub-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://sensehub:sensehub@postgres:5432/sensehub?schema=public"
  S3_ACCESS_KEY: "sensehub"
  S3_SECRET_KEY: "sensehubstorage"
  JWT_SECRET: "replace_me"
  EMBED_SECRET: "replace_me"
  OPENSEARCH_USERNAME: "replace_me"
  OPENSEARCH_PASSWORD: "replace_me"
  SSO_CLIENT_SECRET: "replace_me"
  VAULT_TOKEN: "replace_me"
