apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yml: |
    receivers:
      otlp:
        protocols:
          http:

    exporters:
      logging:
        loglevel: info

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]
