apiVersion: v1
kind: Secret
metadata:
  name: sensehub-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://autoqual:replace_me@postgres.example.com:5432/autoqual?schema=public"
  S3_ACCESS_KEY: "replace_me"
  S3_SECRET_KEY: "replace_me"
  JWT_SECRET: "replace_me"
  EMBED_SECRET: "replace_me"
  OPENSEARCH_USERNAME: "replace_me"
  OPENSEARCH_PASSWORD: "replace_me"
  SSO_CLIENT_SECRET: "replace_me"
  VAULT_TOKEN: "replace_me"
