apiVersion: v1
kind: Secret
metadata:
  name: sensehub-secrets
type: Opaque
stringData:
  DATABASE_URL: "CHANGE_ME"
  S3_ACCESS_KEY: "CHANGE_ME"
  S3_SECRET_KEY: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME"
  EMBED_SECRET: "CHANGE_ME"
  OPENSEARCH_USERNAME: "CHANGE_ME"
  OPENSEARCH_PASSWORD: "CHANGE_ME"
  SSO_CLIENT_SECRET: "CHANGE_ME"
  VAULT_TOKEN: "CHANGE_ME"
