---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensehub-api
  labels:
    app: sensehub-api
  # Annotate with IRSA role ARN in production via kustomize overlay patch:
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/sensehub-api-irsa
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensehub-web
  labels:
    app: sensehub-web
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensehub-worker
  labels:
    app: sensehub-worker
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/sensehub-worker-irsa
automountServiceAccountToken: false
