apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sensehub-secrets
  namespace: sensehub
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: sensehub-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: CHANGE_ME_DATABASE_SECRET_NAME
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: CHANGE_ME_APP_SECRET_NAME
        property: JWT_SECRET
    - secretKey: EMBED_SECRET
      remoteRef:
        key: CHANGE_ME_APP_SECRET_NAME
        property: EMBED_SECRET
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: CHANGE_ME_APP_SECRET_NAME
        property: S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: CHANGE_ME_APP_SECRET_NAME
        property: S3_SECRET_KEY
    - secretKey: OPENSEARCH_USERNAME
      remoteRef:
        key: CHANGE_ME_APP_SECRET_NAME
        property: OPENSEARCH_USERNAME
    - secretKey: OPENSEARCH_PASSWORD
      remoteRef:
        key: CHANGE_ME_APP_SECRET_NAME
        property: OPENSEARCH_PASSWORD
    - secretKey: SSO_CLIENT_SECRET
      remoteRef:
        key: CHANGE_ME_APP_SECRET_NAME
        property: SSO_CLIENT_SECRET
